# Generated by Django 4.2.4 on 2023-08-23 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_category_women_cat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='women',
            old_name='cat_id',
            new_name='cat',
        ),
    ]
