# Generated by Django 4.2.4 on 2023-09-08 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_engine_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='power',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='power_engine', to='women.engine'),
        ),
    ]
