# Generated by Django 4.2.4 on 2023-09-08 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_alter_car_power'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Engine',
        ),
    ]
